databases:
  - name: budultech-db
    databaseName: budultech
    user: budultech
    plan: free

services:
  - type: web
    name: budul-tech
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma db push && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budultech-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://budultech.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
